19-CRUD-agent
JosepSoc/valorant-tracker-dsw pull request #19
Opened 2023-12-14 01:23 UTC by JosepSoc

FInished Crud-agents
changes: 
Created crud-agent with routing.
Changed DialogMaterial from crud-user to sharedModules.
Tweaks for crud-user.
Created agents-api service.

2023-12-14 02:41 UTC, ProDIGGY-vinilos requested changes

2023-12-14 02:41 UTC, ProDIGGY-vinilos commented on front-vtracker/src/app/crud-agent/crud-agent.module.ts
> +    MatIconModule,
son distintos estos iconos con respecto a los de Font awesome ??

2023-12-14 02:41 UTC, ProDIGGY-vinilos commented on front-vtracker/src/app/crud-agent/pages/abm-form/abm-form.component.ts
> +  description = new FormControl('', [Validators.required]);
Esto se puede hacer con formGroup y asi poder enviar los datos como objeto

2023-12-14 02:41 UTC, ProDIGGY-vinilos commented on front-vtracker/src/app/crud-agent/pages/abm-list/abm-list.component.ts
> +
mucho espacio en blanco

2023-12-14 19:35 UTC, JosepSoc commented
Fixed

2023-12-15 00:43 UTC, ProDIGGY-vinilos approved these changes

2023-12-15 00:43 UTC, merged